version: "3.7"

services:
  database:
    image: postgres
    container_name: database_sss
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rekcod
      - POSTGRES_DB=database_sss
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432

  api:
    build: .
    container_name: api_sss
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/api
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local